INSERT INTO `palettes`(`ID`, `theme`, `name`) VALUES (1, 'munich', '##paletteFolder##');

INSERT INTO `palette_colors`(`ID`, `paletteID`, `colorID`, `R`, `G`, `B`, `A`) VALUES (1, 1, 35, 82, 84, 86, 1.00);
INSERT INTO `palette_colors`(`ID`, `paletteID`, `colorID`, `R`, `G`, `B`, `A`) VALUES (2, 1, 36, 0, 0, 0, 1.00);
INSERT INTO `palette_colors`(`ID`, `paletteID`, `colorID`, `R`, `G`, `B`, `A`) VALUES (3, 1, 37, 70, 118, 112, 1.00);
INSERT INTO `palette_colors`(`ID`, `paletteID`, `colorID`, `R`, `G`, `B`, `A`) VALUES (4, 1, 38, 222, 222, 222, 1.00);
INSERT INTO `palette_colors`(`ID`, `paletteID`, `colorID`, `R`, `G`, `B`, `A`) VALUES (5, 1, 39, 18, 17, 24, 1.00);
INSERT INTO `palette_colors`(`ID`, `paletteID`, `colorID`, `R`, `G`, `B`, `A`) VALUES (6, 1, 40, 17, 93, 143, 1.00);
INSERT INTO `palette_colors`(`ID`, `paletteID`, `colorID`, `R`, `G`, `B`, `A`) VALUES (7, 1, 41, 21, 117, 179, 1.00);
INSERT INTO `palette_colors`(`ID`, `paletteID`, `colorID`, `R`, `G`, `B`, `A`) VALUES (8, 1, 42, 105, 179, 227, 1.00);
INSERT INTO `palette_colors`(`ID`, `paletteID`, `colorID`, `R`, `G`, `B`, `A`) VALUES (9, 1, 43, 8, 30, 56, 1.00);
INSERT INTO `palette_colors`(`ID`, `paletteID`, `colorID`, `R`, `G`, `B`, `A`) VALUES (10, 1, 44, 225, 95, 22, 1.00);
INSERT INTO `palette_colors`(`ID`, `paletteID`, `colorID`, `R`, `G`, `B`, `A`) VALUES (11, 1, 45, 235, 118, 53, 1.00);
INSERT INTO `palette_colors`(`ID`, `paletteID`, `colorID`, `R`, `G`, `B`, `A`) VALUES (12, 1, 46, 235, 235, 235, 1.00);
INSERT INTO `palette_colors`(`ID`, `paletteID`, `colorID`, `R`, `G`, `B`, `A`) VALUES (13, 1, 47, 239, 239, 239, 1.00);
INSERT INTO `palette_colors`(`ID`, `paletteID`, `colorID`, `R`, `G`, `B`, `A`) VALUES (14, 1, 48, 26, 24, 42, 1.00);

INSERT INTO `palette_color_schemes`(`ID`, `paletteID`, `name`) VALUES (1, 1, '##paletteFolder##');

INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (1, 1, 'NAVIGATION_SELECTED_BG_COLOR', 1);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (2, 1, 'NAVIGATION_HOVER_BG_COLOR', 1);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (3, 1, 'NAVIGATION_TEXT_COLOR_SELECTED', 36);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (4, 1, 'FOOTER_BG_COLOR', 43);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (5, 1, 'FOOTER_TEXT_COLOR', 38);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (6, 1, 'FOOTER_LINK_COLOR', 38);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (7, 1, 'NAVIGATION_TEXT_COLOR', 39);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (8, 1, 'BS_BTN_PRIMARY_BG', 44);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (9, 1, 'BS_BTN_PRIMARY_BORDER', 44);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (10, 1, 'BS_BTN_PRIMARY_HOVER_BG', 45);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (11, 1, 'BS_BTN_PRIMARY_HOVER_BORDER', 45);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (12, 1, 'NOD_ARTICLE_LIST_SECTION_BORDER_ACTIVE_COLOR', 40);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (13, 1, 'NOD_ARTICLE_LIST_SECTION_BORDER_HOVER_COLOR', 41);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (14, 1, 'NOD_ARTICLE_LIST_SECTION_HOVER_COLOR', 41);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (15, 1, 'NOD_ARTICLE_LIST_PAGINATION_ACTIVE_BG_COLOR', 40);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (16, 1, 'INPUT_HOVER_BORDER_COLOR', 40);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (17, 1, 'INPUT_FOCUS_BORDER_COLOR', 40);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (18, 1, 'NOD_ARTICLE_LIST_SECTION_ACTIVE_COLOR', 40);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (19, 1, 'BS_BTN_SUCCESS_BG', 44);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (20, 1, 'BS_BTN_SUCCESS_HOVER_BG', 45);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (21, 1, 'MAIN_FIELD_CHECKBOX_COLOR_SELECTED', 11);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (22, 1, 'HEADER_TOP_BAR_COLOR', 42);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (23, 1, 'NAVIGATION_HOVER_TEXT_COLOR', 39);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (24, 1, 'NAVIGATION_BORDER_COLOR', 1);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (25, 1, 'BS_BTN_PRIMARY_COLOR', 46);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (26, 1, 'BS_BTN_PRIMARY_HOVER_COLOR', 46);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (27, 1, 'BS_BTN_SUCCESS_HOVER_COLOR', 46);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (28, 1, 'BS_BTN_SUCCESS_COLOR', 46);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (29, 1, 'BODY_COLOR', 48);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (30, 1, 'HX_COLOR', 48);
INSERT INTO `palette_color_scheme_colors`(`ID`, `schemeID`, `constant`, `colorID`) VALUES (31, 1, 'MAIN_BG_COLOR', 42);
